### ISSUE TITLE
Key storage

### ISSUE THREAD

**Issue by makeworld-the-better-one** [robinsloan/spring-83-spec#2]
The client only saves the key pair in session storage, so it goes away after closing the tab. I understand this is intentional, but IMO it would be better to keep it around by storing it in local storage.

Hope I'm not overloading you, let me know if I am. I can look into making a PR for this if you'd prefer.

**Comment by robinsloan** [comment]
That's a good note. I got stressed out thinking about keeping a secret key in `localStorage`, and that might still stress me out in a "public web app" context, but certainly, in this experimental phase, it's fine. Changed!

(The Springfile will also persist now. That was a leftover bit of dev logic; so yes, basically a bug!)

**Comment by makeworld-the-better-one** [comment]
It seems a lot of places say don't store secrets in local storage or session storage, because malicious javascript (from XSS or CDNs) can access those tokens. However someone smart [pointed out](https://stackoverflow.com/a/44318395) that if malicious javascript is involved it's already game over anyway. So I think it's fine. Thanks for making the change!
